name: portfolio
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.2.1
  fluttericon: ^2.0.0
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  intl_utils: ^2.8.1
  build_runner: ^2.0.4
  build_web_compilers: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/social/
    - assets/icon/experience/

flutter_intl:
  main_locale: en_US
  enabled: true
